version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    image: frontend
    container_name: nuxt-app
    restart: always
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'

networks:
  dev-network:
    driver: bridge
